FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: Native Messaging
desc: Configures policies for Native Messaging. Blocked native messaging hosts won't
  be allowed unless they are whitelisted.
