FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
source_set("coordinator") {
  sources = [
    "composebox_picker_image_result.h",
    "composebox_picker_image_result.mm",
    "composebox_picker_presenter.h",
    "composebox_picker_presenter.mm",
  ]
  deps = [
    "//base",
    "//components/lens",
  ]
}
