FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
source_set("launchd") {
  sources = [
    "launchd.h",
    "launchd.mm",
    "service_management.h",
    "service_management.mm",
  ]

  deps = [ "//base" ]

  libs = [
    "CoreServices.framework",
    "Foundation.framework",
    "ServiceManagement.framework",
  ]
}
