FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2021 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

css_files = [
  "button.css",
  "custom_toast.css",
  "flash.css",
  "inkdrop.css",
  "main.css",
  "menu.css",
  "mode/mode.css",
  "mode/scan.css",
  "mode/video.css",
  "ptz_panel.css",
  "review.css",
  "views/settings.css",
]
