FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

static_library("renderer") {
  sources = [
    "net_error_helper_core.cc",
    "net_error_helper_core.h",
  ]

  deps = [
    "//base",
    "//components/error_page/common",
    "//components/strings",
    "//content/public/common",
    "//net",
    "//third_party/WebKit/public:blink",
    "//ui/base",
    "//url",
  ]
}
