FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2018 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("unit_tests") {
  testonly = true

  deps = [
    "//base/test:test_support",
    "//media:test_support",
    "//media/learning/common:unit_tests",
    "//media/learning/impl:unit_tests",
    "//testing/gtest",
  ]
}
