FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
import("//testing/libfuzzer/fuzzer_test.gni")

source_set("fuzzy_finder") {
  sources = [
    "fuzzy_finder.cc",
    "fuzzy_finder.h",
  ]

  configs += [ "//build/config/compiler:wexit_time_destructors" ]

  deps = [
    "//base:base",
    "//base:i18n",
    "//ui/gfx/range",
  ]
}

fuzzer_test("fuzzy_finder_fuzzer") {
  sources = [ "fuzzy_finder_fuzzer.cc" ]
  deps = [
    ":fuzzy_finder",
    "//base:base",
  ]
}
