FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
static_library("debug") {
  sources = [
    "structured_metrics_utils.cc",
    "structured_metrics_utils.h",
    "structured_metrics_watcher.cc",
    "structured_metrics_watcher.h",
  ]
  deps = [
    "//base",
    "//base:i18n",
    "//components/metrics/structured",
  ]
}
