FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: Local Network Access settings
desc: A group of policies related to Local Network Access settings.  See https://developer.chrome.com/blog/local-network-access
