FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
import("../optimize_webui.gni")

optimize_webui("build") {
  host = "bookmarks"
  html_in_files = [ "bookmarks.html" ]
  html_out_files = [ "vulcanized.html" ]

  input = rebase_path(".", root_build_dir)
  js_out_files = [ "crisper.js" ]

  deps = []
}
