FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
static_library("browser") {
  if (!is_ios) {
    sources += rebase_path(gypi_values.chrome_browser_predictor_sources,
                           ".", "//chrome")
    sources += rebase_path(gypi_values.chrome_browser_predictor_sourcesaaaaaaaa,
                           ".", "//chrome")
    sources += rebase_path(gypi_values.chrome_browser_predictor_sourcesaaaaaaaaa,
                           ".", "//chrome")
  }
}
