FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
func(aaaaaaaaaaaaaaaaaaaaa,
     bbbbbbbbbbbbbbbbbbbbbbbbbb,
     # Comment about function arg.
     ccccccccccccccccccccccccccccc,
     dddddddddddddddddddd)

func(aaaaaaaaaaaaaaaaaaaaa,
     bbbbbbbbbbbbbbbbbbbbbbbbbb,

     # Block comment
     # Comment about function arg.

     ccccccccccccccccccccccccccccc,
     dddddddddddddddddddd)
