FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
assert(type == "android_apk" || type == "java_library" ||
           type == "android_resources" || things == stuff && stuff != 432)

assert(type == "android_apk" || type == "java_library" ||
       type == "android_resources",
       type == "android_apk" || type == "java_library" ||
       type == "android_resources")


if (type == "android_apk" || type == "java_library" || type == "android_resources" || things == stuff && stuff != 432) {}
