FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: Device update settings
desc: Controls how and when <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph>
  updates are applied.
