FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

ntp_promo_ts_files = [
  "ntp_promo/ntp_promo_proxy.ts",
  "ntp_promo/individual_promos.ts",
  "ntp_promo/individual_promos.html.ts",
]

ntp_promo_css_files = [ "ntp_promo/individual_promos.css" ]
