FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: <ph name="MS_AD_NAME">Microsoft® Active Directory®</ph> management settings
desc: Controls settings specific to <ph name="MS_AD_NAME">Microsoft® Active Directory®</ph>
  managed <ph name="PRODUCT_OS_NAME">$2<ex>Google ChromeOS</ex></ph> devices.
