FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: Content settings
desc: Content settings allow you to specify how contents of a specific type (for example
  Cookies, Images or JavaScript) is handled.
