FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
source_set("intents_donation_helper") {
  sources = [
    "intents_donation_helper.h",
    "intents_donation_helper.mm",
  ]
  deps = [
    "//base",
    "//ios/chrome/app/strings",
    "//ios/chrome/app/strings:ios_strings",
    "//ios/chrome/common/intents",
    "//ui/base",
  ]
  frameworks = [
    "Intents.framework",
    "Foundation.framework",
  ]
}
