FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
caption: Parental supervision settings
desc: |-
  Controls parental supervision policies, that are applied to child accounts only.
        These policies are not set in the admin console, but configured directly by Kids API Server.
