FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
application: chromeextensionsdocs
version: 1-2-2
runtime: python
api_version: 1

handlers:
- url: /.*
  script: chromeextensionsdocs.py
