FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2020 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("scoped_iphone_portrait_only") {
  sources = [
    "iphone_portrait_only_manager.h",
    "scoped_iphone_portrait_only.h",
    "scoped_iphone_portrait_only.mm",
  ]
  deps = [
    "//base",
    "//ui/base",
  ]
}
