FASTVC-BENCH-CORPUS:chromium-main-v1-943b94ae-1c74-4335-94fa-ceb4d277cea8
# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if (is_android) {
  declare_args() {
    # If true, build the player UI and playback code as a preinstalled isolated
    # split APK to save chrome.apk binary size. Otherwise build it into
    # chrome.apk.
    readaloud_player_split_module = true
  }
}
